apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: privat-pgi-inntekt
  namespace: pensjonopptjening
  labels:
    team: pensjonopptjening
spec:
  pool: nav-dev
  config:
    cleanupPolicy: delete
    minimumInSyncReplicas: 1
    partitions: 3
    replication: 3
    retentionBytes: -1 # Messages will never get deleted because of disk space
    retentionHours: 2193 # Messages are stored for 3 months
  acl:
    - team: pensjonopptjening
      application: pgi-les-inntekt-skatt
      access: write
    - team: pensjonopptjening
      application: pgi-lagre-inntekt-popp
      access: read
