apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: privat-pgi-nextsekvensnummer
  namespace: pensjonopptjening
  labels:
    team: pensjonopptjening
spec:
  pool: prod-gcp
  config:
    cleanupPolicy: compact # Kafka will only store _at least_ the last message produced to a topic, for a specific key
    minimumInSyncReplicas: 1
    partitions: 1
    replication: 3
    retentionBytes: -1 # Messages will never get deleted because of disk space
    retentionHours: 8737 # Messages are stored for one year before deletion
  acl:
    - team: pensjonopptjening
      application: pgi-les-hendelse-skatt
      access: readwrite
