apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: privat-pgi-hendelse-republisering
  namespace: pensjonopptjening
  labels:
    team: pensjonopptjening
spec:
  pool: {{kafka-pool}}
  config:
    cleanupPolicy: delete # Kafka will discard old segments when retention time or size limit has been reached
    minimumInSyncReplicas: 1
    partitions: 1
    replication: 3
    retentionBytes: -1 # Messages will never get deleted because of disk space
    retentionHours: 2193 # Messages are stored for 3 months
  acl:
    - team: pensjonopptjening
      application: pgi-republiser-hendelse
      access: read
    - team: pensjonopptjening
      application: pgi-lagre-inntekt-popp # Rekjøring av hendelser hvis korresponderende inntekt feiler mot POPP
      access: write
