apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: privat-pgi-inntekt
  namespace: pensjonsamhandling
  labels:
    team: pensjonsamhandling
spec:
  pool: {{kafka-pool}}
  config:
    cleanupPolicy: delete
    minimumInSyncReplicas: 1
    partitions: 3
    replication: 3
    retentionBytes: -1 # Messages will never get deleted because of disk space
    retentionHours: 2193 # Messages are stored for 3 months
  acl:
    - team: pensjonsamhandling
      application: pgi-les-inntekt-skatt
      access: write
    - team: pensjonsamhandling
      application: pgi-lagre-inntekt-popp
      access: read
