name: Release topic changes prod-gcp

on:
  workflow_dispatch:

jobs:
  deploy-to-prod:
    name: Deploy to prod-gcp
    permissions:
      contents: "read"
      id-token: "write"  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Release changes for pgi topics
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: topics/prod/privat-pgi-nextsekvensnummer.yaml,topics/prod/privat-pgi-hendelse.yaml,topics/prod/privat-pgi-inntekt.yaml,topics/prod/privat-pgi-hendelse-republisering.yaml
